In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt 

In [2]:
df=pd.read_csv('Customer-Churn-Prediction.csv')
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [4]:
df.describe()

SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162289    32.370865       64.761692
std         0.368742    24.559231       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [5]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
#Copy Df dataset for using upcoming methods 

df1=df.copy()
df2=df.copy()
df3=df.copy()

In [7]:
df.shape

(7043, 21)

In [8]:
df['Churn'].value_counts()

No     5174
Yes    1869
Name: Churn, dtype: int64

# Preprocessing Dataset

In [9]:
df=df.drop(['customerID'],axis=1)

In [10]:
df.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0              Yes           Electronic check           29.85        29.85   
1               No               Mailed check           56.95       1889.5   
2              Yes               Mailed check           53.85       108.15   
3               No  Bank transfer (automatic)           42.30      1840.75   
4              Yes           Electronic check           70.70       151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

In [11]:
#using Label Encoder for preprocess my dataset

from sklearn.preprocessing import LabelEncoder 
Label=LabelEncoder()

In [12]:
from pandas.core.dtypes.common import is_numeric_dtype
for column in df.columns:
    if is_numeric_dtype(df[column]):
        continue 
    else:
        df[column]=Label.fit_transform(df[column])

In [13]:
df.head() #The Dataset is showing after using Label Encoding

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0   
1       1              0        0           0      34             1   
2       1              0        0           0       2             1   
3       1              0        0           0      45             0   
4       0              0        0           0       2             1   

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0              1                0               0             2   
1              0                0               2             0   
2              0                0               2             2   
3              1                0               2             0   
4              0                1               0             0   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 0            0            0                0         0   
1                 2            0            0                0         1   
2                 0            0            0                0         0   
3                 2            2            0                0         1   
4                 0            0            0                0         0   

   PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0                 1              2           29.85          2505      0  
1                 0              3           56.95          1466      0  
2                 1              3           53.85           157      1  
3                 0              0           42.30          1400      0  
4                 1              2           70.70           925      1

# Seperate Dependent and Independent Variables 

In [14]:
x=df.drop(['Churn'], axis=1)
x.shape

(7043, 19)

In [15]:
y=df['Churn']
y.shape

(7043,)

# Handle Imbalance Data with SMOTETomek, Under and Over sampling Method

In [16]:
!pip install imblearn


In [17]:
from imblearn.combine import SMOTETomek

In [18]:
SMOT=SMOTETomek()

In [19]:
X,Y=SMOT.fit_resample(x,y)

In [20]:
X.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0   
1       1              0        0           0      34             1   
2       1              0        0           0      45             0   
3       0              0        0           0       2             1   
4       0              0        0           0       8             1   

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0              1                0               0             2   
1              0                0               2             0   
2              1                0               2             0   
3              0                1               0             0   
4              2                1               0             0   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 0            0            0                0         0   
1                 2            0            0                0         1   
2                 2            2            0                0         1   
3                 0            0            0                0         0   
4                 2            0            2                2         0   

   PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  
0                 1              2           29.85          2505  
1                 0              3           56.95          1466  
2                 0              0           42.30          1400  
3                 1              2           70.70           925  
4                 1              2           99.65          6104

In [21]:
X.shape

(9654, 19)

In [22]:
Y.shape

(9654,)

In [23]:
Y.value_counts()

0    4827
1    4827
Name: Churn, dtype: int64

# Near Miss for Under_Sampling

In [24]:
from imblearn.under_sampling import NearMiss

In [25]:
NEM=NearMiss()

In [26]:
X1,Y1=NEM.fit_resample(x,y)

In [27]:
Y1.shape

(3738,)

In [28]:
Y1.value_counts()

0    1869
1    1869
Name: Churn, dtype: int64

# Over Sampling 

In [29]:
df1.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [30]:
df2.Churn.value_counts()

No     5174
Yes    1869
Name: Churn, dtype: int64

In [31]:
from imblearn.over_sampling import RandomOverSampler
ROS= RandomOverSampler()

In [32]:
new_x, new_y=ROS.fit_resample(x,y)

In [33]:
new_x.shape

(10348, 19)

In [34]:
new_y.shape

(10348,)

# Cross Validation

# HOLD and K-Fold cross validation

In [35]:
#...............Hold Out Cross Validation.............

from sklearn.model_selection import train_test_split
xtrain,xtest, ytrain,ytest = train_test_split(x, y, train_size=.75,random_state=42) 

In [36]:
#............Decission TreeClasifer.............

from sklearn.tree import DecisionTreeClassifier
DTC=DecisionTreeClassifier()
DTC.fit(xtrain, ytrain)
DTC.score(xtest,ytest)

0.7206132879045997

In [37]:
#.............AdaBoost.............

from sklearn.ensemble import AdaBoostClassifier
ADB=AdaBoostClassifier()
ADB.fit(xtrain, ytrain)
ADB.score(xtest, ytest)

0.797274275979557

In [38]:
#..........K-Fold Cross Validation.................


from sklearn.model_selection import KFold, cross_val_score
kfold = KFold(n_splits=5) # k=5 means it seperate with five section

In [39]:
#............Decission TreeClasifer for K-fold.............


result = cross_val_score(DTC,x,y,cv=kfold) 
result

array([0.73456352, 0.74095103, 0.72817601, 0.70099432, 0.74076705])

In [40]:
result.max(), result.min()

(0.7409510290986515, 0.7009943181818182)

In [41]:
result.mean()

0.7290903848635396

In [42]:
#.............AdaBoost for for K-fold.............

result1 = cross_val_score(ADB,x,y,cv=kfold) 
result1

array([0.8105039 , 0.80766501, 0.79630944, 0.79261364, 0.80184659])

In [43]:
result1.mean()

0.801787716142977

# Stratified k fold cross Validation¶

In [44]:
from sklearn.model_selection import StratifiedKFold
STK = StratifiedKFold(n_splits=5)

In [45]:
#............Decission TreeClasifer for Stratified K-fold.............

result2= cross_val_score(DTC,x,y,cv=STK) 
result2

array([0.7338538 , 0.7217885 , 0.7217885 , 0.70525568, 0.74289773])

In [46]:
result2.max(), result2.min()

(0.7428977272727273, 0.7052556818181818)

In [47]:
result2.mean()

0.7251168422156269

In [48]:
#.............AdaBoost for Stratified K-fold.............

result2 = cross_val_score(ADB,x,y,cv=STK) 
result2

array([0.8105039 , 0.80269695, 0.7920511 , 0.80610795, 0.80184659])

In [49]:
result2.max(), result2.min()

(0.8105039034776437, 0.7920511000709723)

In [50]:
result2.mean()

0.8026412994386736